image:
  repository: spooky/logic
  tag: 1.0-ga
service:
  type: ClusterIP
  port: 8080
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: true
  host: spooky.yourdomain.tld
